---
server:
  port: 6789
spring:
  application:
    name: restaurant
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1234/eureka/
  instance:
    hostname: localhost
    
 #  datasource:
#    url: jdbc:postgresql://localhost:5432/sbdb
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: craete
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
